
import { ScheduleItem } from '../types';

const formatDateTimeForICS = (date: Date): string => {
  const year = date.getUTCFullYear();
  const month = (date.getUTCMonth() + 1).toString().padStart(2, '0');
  const day = date.getUTCDate().toString().padStart(2, '0');
  const hours = date.getUTCHours().toString().padStart(2, '0');
  const minutes = date.getUTCMinutes().toString().padStart(2, '0');
  const seconds = date.getUTCSeconds().toString().padStart(2, '0');
  return `${year}${month}${day}T${hours}${minutes}${seconds}Z`;
};

export const generateICSFileContent = (schedule: ScheduleItem[]): string => {
  let icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//JEEPrepPlanner//EN',
    'CALSCALE:GREGORIAN',
  ];

  schedule.forEach(item => {
    const event = [
      'BEGIN:VEVENT',
      `UID:${item.chapterId}@jeepplanner.com`,
      `DTSTAMP:${formatDateTimeForICS(new Date())}`,
      `DTSTART:${formatDateTimeForICS(item.startTime)}`,
      `DTEND:${formatDateTimeForICS(item.endTime)}`,
      `SUMMARY:Study: ${item.chapter} (${item.subject})`,
      'DESCRIPTION:Generated by JEE Prep Planner.',
      'END:VEVENT',
    ];
    icsContent.push(...event);
  });

  icsContent.push('END:VCALENDAR');
  return icsContent.join('\r\n');
};
